apiVersion: v1
kind: Service
metadata:
  name: foodgo-frontend
  namespace: foodgo
  labels:
    app: foodgo-frontend
spec:
  type: ClusterIP
  selector:
    app: foodgo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
